In [1]:
import requests
# xml 파일을 읽어오기 위해 필요함
from lxml import html
# 태그형태의 데이터를 추출하기 위해 필요함
from bs4 import BeautifulSoup
import pandas as pd
# 아래 두줄은 url인코더를 하기 위해 필요함
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus, unquote

response = requests.get("http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev?serviceKey=AT33s775KYpJOkUBJu0dxkJuUeIfDIOJRzAH084EQS3JN%2BzFjErLHuk%2FGZa9L4gBTSGCzeA69tI9PwLp7B37IQ%3D%3D&pageNo=1&numOfRows=10&LAWD_CD=11110&DEAL_YMD=201512")

# 인코딩하기
response.encoding = 'utf-8'

# parser
xmlobj = BeautifulSoup(response.text,"lxml-xml")

# item태그안에 있는 내용 찾기
rows = xmlobj.find_all("item")

# 사용할 배열 초기화
rowList = []
columnList = []
columnsNameList = []

for i in range(0, len(rows)):

    eachRow = rows[i]

    columns = eachRow.find_all() 


    for j in range(0, len(columns)):
        eachColumns = columns[j]

        if i == 0:
            # name은 이름이 나오는것
            columnsNameList.append(eachColumns.name)

        # text내용이나옴
        eachColumnsValue = eachColumns.text


        columnList.append(eachColumnsValue.replace(" ",""))
    
    rowList.append(columnList)
    columnList = []

In [6]:
pd.DataFrame(rowList, columns = columnsNameList).head()

,거래금액,건축년도,년,도로명,도로명건물본번호코드,도로명건물부번호코드,도로명시군구코드,도로명일련번호코드,도로명지상지하코드,도로명코드,...,아파트,월,일,일련번호,전용면적,지번,지역코드,층,해제사유발생일,해제여부
0,"82,500",2008,2015,사직로8길,00004,00000,11110,03,0,4100135,...,광화문풍림스페이스본(101동~105동),12,10,11110-2203,94.51,9,11110,11,,
1,"60,000",1981,2015,세종대로23길,00047,00000,11110,02,0,4100190,...,롯데미도파광화문빌딩,12,22,11110-12,149.95,145,11110,8,,
2,"130,000",2004,2015,경희궁2길,00005,00005,11110,01,0,4100005,...,킹스매너,12,8,11110-118,194.43,110-15,11110,6,,
3,"105,000",2004,2015,사직로8길,00024,00000,11110,05,0,4100135,...,경희궁의아침2단지,12,14,11110-115,124.17,71,11110,8,,
4,"120,000",2003,2015,사직로8길,00020,00000,11110,05,0,4100135,...,경희궁파크팰리스,12,24,11110-107,146.33,95,11110,4,,